### ISSUE TITLE
Wrong name of the libraries

### ISSUE THREAD

**Issue by GoogleCodeExporter** [qextserialport/qextserialport#177]
```
Which version of QextSerialPort are you using?
1.2 RC

What steps will reproduce the problem?
1. Generate de libraries and .dll and then run mingw32-make install

What is the expected output? What do you see instead?
Expected libraries are libQt5ExtSerialPortd.a and libQt5ExtSerialPort.a
instead the libraries that are copied are libQt5ExtSerialPortd1.a and 
libQt5ExtSerialPort1.a

changing the name solves the problem.

What version of the product are you using? On what operating system?
Qt 5.2 on Win XP


```

Original issue reported on code.google.com by `agustin....@gmail.com` on 26 Jan 2014 at 11:41

**Comment by sirpete83** [comment]
Hi,
after creating the dll with the minqw32-make and install, the Qt5ExtSerialPort1.dll is created but linker tries to link to Qt5ExtSerialPort.dll but the now compilied executable needs the Qt5ExtSerialPort1.dll in the working dir.
how the solve the problem without renaming the dll for the linker?
